### ISSUE TITLE
Lots of errors when starting up forge 31.1 and client doesn't load the mods

### ISSUE THREAD

**Issue by mbrucher** [AllTheMods/ATM-5#19]
Hi all, quite a newbie here.
I just added the latest All the Mods 5 on a fresh forge 31.1 (so installing forge then copying the mods in the mods folder).
It looks like there is lots of red lines there, is it expected?
Also there is no mods loaded in my Forge 31.1 client (I copied the content of the zip files in the mods folder, as explained online).

Server runs on Linux Mint, client is the official (no Twitch) on Windows 10.

**Comment by mbrucher** [comment]
Tried through Twitch (with the latest 64bits JRE8), now the launcher breqks:

[21:55:49 INFO]: Minecraft Launcher 1.6.91 (through bootstrap 100) started on windows...
[21:55:49 INFO]: Current time is Feb 6, 2020 9:55:49 PM
[21:55:49 INFO]: System.getProperty('os.name') == 'Windows 10'
[21:55:49 INFO]: System.getProperty('os.version') == '10.0'
[21:55:49 INFO]: System.getProperty('os.arch') == 'amd64'
[21:55:49 INFO]: System.getProperty('java.version') == '1.8.0_241'
[21:55:49 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[21:55:49 INFO]: System.getProperty('sun.arch.data.model') == '64'
[21:55:49 INFO]: proxy == DIRECT
[21:55:50 INFO]: JFX is already initialized
[21:55:50 INFO]: Refreshing local version list...
[21:55:50 INFO]: Refreshing remote version list...
[21:55:50 INFO]: Refresh complete.
[21:55:50 ERROR]: Unexpected exception refreshing profile list
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher.jar:1.6.91]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher.jar:1.6.91]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:32) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:213) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:268) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.CompleteMinecraftVersion.resolve(CompleteMinecraftVersion.java:255) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersionSyncInfo(MinecraftVersionManager.java:171) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getVersions(MinecraftVersionManager.java:105) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.game.GameLaunchDispatcher.getStatus(GameLaunchDispatcher.java:35) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.checkState(PlayButtonPanel.java:94) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.ui.bottombar.PlayButtonPanel.onProfilesRefreshed(PlayButtonPanel.java:90) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.profile.ProfileManager.fireRefreshEvent(ProfileManager.java:100) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.profile.ProfileManager.loadProfiles(ProfileManager.java:88) ~[launcher.jar:1.6.91]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:183) [launcher.jar:1.6.91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[21:55:50 INFO]: Refreshing auth...
[21:55:50 INFO]: Logging in with access token
[21:55:50 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
