### ISSUE TITLE
hope this helps

### ISSUE THREAD

**Issue by jogborn** [AllTheMods/ATM-5#31]

**Comment by jogborn** [comment]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 3/5/20 9:08 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Biomes O' Plenty (biomesoplenty) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3450274656 bytes (3290 MB) / 5115478016 bytes (4878 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx6144M -Xms3000M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		AdditionalEnchantedMiner-1.15.2-15.2.1.jar QuarryPlus {quarryplus@15.2.1 CREATE_REGISTRIES}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 CREATE_REGISTRIES}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 CREATE_REGISTRIES}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 CREATE_REGISTRIES}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 CREATE_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 CREATE_REGISTRIES}
		rsgauges-1.15.2-1.2.1.jar Gauges and Switches {rsgauges@1.2.1 CREATE_REGISTRIES}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 CREATE_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 CREATE_REGISTRIES}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		Powah-1.15.2-1.1.6.jar Powah {powah@1.1.6 CREATE_REGISTRIES}
		dimensionalworld-1.0.0.jar Buuz135DimensionalWorld {dimensionalworld@NONE CREATE_REGISTRIES}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 CREATE_REGISTRIES}
		potionsmaster-0.0.12-1.15.2-31.1.18.jar Potions Master {potionsmaster@0.0.12 CREATE_REGISTRIES}
		potionofbees-1.15.2-1.0.0.jar Potion of Bees {potionofbees@1.15.2-1.0.0 CREATE_REGISTRIES}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.0.5.jar Apotheosis {apotheosis@3.0.5 CREATE_REGISTRIES}
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 CREATE_REGISTRIES}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.11.403.jar Mekanism: Generators {mekanismgenerators@9.9.11 CREATE_REGISTRIES}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 CREATE_REGISTRIES}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 CREATE_REGISTRIES}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  CREATE_REGISTRIES}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 CREATE_REGISTRIES}
		PackMenu-1.15.2-1.2.3.jar Pack Menu {packmenu@1.2.3 CREATE_REGISTRIES}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 CREATE_REGISTRIES}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 CREATE_REGISTRIES}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 CREATE_REGISTRIES}
		AdPoles-1.15.2-4.0.0.0-build.0004.jar To the Bat Poles! {adpoles@4.0.0.0 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 ERROR}
		MekanismAdditions-1.15.2-9.9.11.403.jar Mekanism: Additions {mekanismadditions@9.9.11 CREATE_REGISTRIES}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 CREATE_REGISTRIES}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE CREATE_REGISTRIES}
		Lollipop-1.15.2-1.0.8.jar Lollipop {lollipop@1.0.8 CREATE_REGISTRIES}
		mining_dimension-1.15.2-1.0.1.jar Mining World {mining_dimension@1.15.2-1.0.1 CREATE_REGISTRIES}
		SilentGear-1.15.2-1.5.2+77.jar Silent Gear {silentgear@1.5.2+77 CREATE_REGISTRIES}
		tgcropesmod-1.15.2-1.2.0.jar Ropes Mod {tgcropesmod@1.15.2-1.2.0 CREATE_REGISTRIES}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 CREATE_REGISTRIES}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 CREATE_REGISTRIES}
		corail_woodcutter-1.1.1-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.1 CREATE_REGISTRIES}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 CREATE_REGISTRIES}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 CREATE_REGISTRIES}
		tombstone-4.2.4-1.15.2.jar Corail Tombstone {tombstone@4.2.4 CREATE_REGISTRIES}
		NaturesAura-23.1.jar Nature's Aura {naturesaura@version CREATE_REGISTRIES}
		MekanismTools-1.15.2-9.9.11.403.jar Mekanism: Tools {mekanismtools@9.9.11 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		tramplestopper-1.15.2-2.0.0.5-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.5-universal CREATE_REGISTRIES}
		the_bumblezone-1.15.2-1.0.4.jar The Bumblezone {the_bumblezone@1.15.2-1.0.4 CREATE_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 CREATE_REGISTRIES}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.1.11.jar Cyclic {cyclic@1.15.2-0.1.11 CREATE_REGISTRIES}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 CREATE_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		Ma-Enchants-1.15.2-3.0.0.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 CREATE_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 CREATE_REGISTRIES}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 CREATE_REGISTRIES}
		buzzierbees-1.1.4.jar Buzzier Bees {buzzierbees@1.1.4 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.9.11.403.jar Mekanism {mekanism@9.9.11 CREATE_REGISTRIES}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 CREATE_REGISTRIES}
		reap-1.12.1.jar Reap Mod {reap@1.12.1 CREATE_REGISTRIES}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 CREATE_REGISTRIES}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 CREATE_REGISTRIES}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 CREATE_REGISTRIES}
		enviromats-1.15.2-2.0.2.1.jar Environmental Materials {enviromats@1.15.2-2.0.2.1 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		EnderBags-1.15.1-5.0.0.jar Ender Bags {ender_bags@5.0.0 CREATE_REGISTRIES}
		additionalbars-1.2.1.jar Additional Bars {additionalbars@1.2.1 CREATE_REGISTRIES}
		SimpleStorageNetwork-1.15.2-0.2.4.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 CREATE_REGISTRIES}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 CREATE_REGISTRIES}
		engineerstools-1.15.2-1.0.6-b2.jar Engineer's Tools {engineerstools@1.0.6-b2 CREATE_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha CREATE_REGISTRIES}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha CREATE_REGISTRIES}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha CREATE_REGISTRIES}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha CREATE_REGISTRIES}
		ClickMachine-1.15.2-3.0.1.jar Click Machine {clickmachine@3.0.1 CREATE_REGISTRIES}
		environmentalcreepers-forge-1.15.2-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 CREATE_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 CREATE_REGISTRIES}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 CREATE_REGISTRIES}
		CraftTweaker-1.15.2-6.0.0.9.jar CraftTweaker {crafttweaker@6.0.0.9 CREATE_REGISTRIES}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha CREATE_REGISTRIES}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 CREATE_REGISTRIES}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 CREATE_REGISTRIES}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 CREATE_REGISTRIES}
		PassthroughSigns-1.15.1-2.3.2.jar Passthrough Signs {passthroughsigns@1.15.1-2.3.2 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 CREATE_REGISTRIES}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 CREATE_REGISTRIES}
		forge-1.15.2-31.1.18-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b CREATE_REGISTRIES}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b CREATE_REGISTRIES}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ToolBelt-1.15.2-1.14.0.jar Tool Belt {toolbelt@1.14.0 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 CREATE_REGISTRIES}
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 CREATE_REGISTRIES}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 CREATE_REGISTRIES}
		bluepower-1.15.2-0.4.184-alpha-universal.jar Blue Power {bluepower@0.4.184-alpha CREATE_REGISTRIES}
		allthemodium-0.5.jar Allthemodium {allthemodium@0.5 CREATE_REGISTRIES}
		ExtraButtons-1.15.2-3.0.0.jar ExtraButtons {extrabuttons@1.15.2-3.0.0 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 CREATE_REGISTRIES}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b CREATE_REGISTRIES}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version CREATE_REGISTRIES}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha CREATE_REGISTRIES}
		JAOPCA-1.15.2-3.0.0.20.jar JAOPCA {jaopca@3.0.0.20 CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		[1.15.2] SecurityCraft v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 CREATE_REGISTRIES}
		tubesreloaded-1.15.2-1.3.0b.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0b CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		engineersdecor-1.15.2-1.0.19-b5.jar Engineer's Decor {engineersdecor@1.0.19-b5 CREATE_REGISTRIES}
		RefinedRelocation_1.15.2-7.0.1.jar Refined Relocation {refinedrelocation@7.0.1 CREATE_REGISTRIES}
		allthetweaks-0.6.jar All The Tweaks {allthetweaks@0.6 CREATE_REGISTRIES}
		u_team_core-1.15.2-2.10.6.155.jar U Team Core {uteamcore@2.10.6.155 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 CREATE_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 CREATE_REGISTRIES}
		Ma-Essentials-1.15.2-3.0.1.jar Ma Essentials {ma-essentials@1.15.2-3.0.1 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.15.2-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v1a CREATE_REGISTRIES}
		xptome-1.15.1-v1.1.4.jar XP Tome {xpbook@v1.1.4 CREATE_REGISTRIES}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 CREATE_REGISTRIES}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by jogborn** [comment]
updated Biomes O' Plenty to .348 and server starts now.
